# Generated by Django 2.2.7 on 2019-11-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(max_length=200)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to='usuario.Usuario')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='usuario.Usuario')),
            ],
        ),
    ]
