# Generated by Django 2.2.7 on 2019-11-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala.Sala'),
        ),
    ]
