# Generated by Django 2.2.7 on 2019-11-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0003_auto_20191121_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to='usuario.Usuario'),
        ),
    ]
