# Generated by Django 2.2.7 on 2019-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
                ('senha', models.CharField(max_length=120)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
