# Generated by Django 2.2.7 on 2019-11-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.CharField(default='CAVALO', max_length=500),
            preserve_default=False,
        ),
    ]
